CREATE FUNCTION add_one(integer) RETURNS integer
AS 'MODULE_PATHNAME'
     LANGUAGE C STRICT;

CREATE FUNCTION copytext(text) RETURNS text
AS 'MODULE_PATHNAME'
     LANGUAGE C STRICT;

CREATE FUNCTION concat_text(text, text) RETURNS text
AS 'MODULE_PATHNAME'
     LANGUAGE C STRICT;

CREATE FUNCTION pgupper(text) RETURNS text
AS 'MODULE_PATHNAME'
     LANGUAGE C STRICT;

CREATE FUNCTION pyupper(text) RETURNS text
AS 'MODULE_PATHNAME'
     LANGUAGE C STRICT;

CREATE FUNCTION jsonb_llm_generate(jsonb, text) RETURNS jsonb
AS 'MODULE_PATHNAME'
     LANGUAGE C STRICT;

CREATE FUNCTION jsonb_llm_embed(jsonb, text) RETURNS jsonb
AS 'MODULE_PATHNAME'
     LANGUAGE C STRICT;